#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School is the best" > /var/www/html/index.html
sudo service nginx start
