#!/usr/bin/env bash
# script that install nginx and configure it to return custom 404 page not found erorr
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School is the best" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# codes to redirect a specific endpoint
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/jbyiringiro permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# codes to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404notfound.html > /dev/null
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404notfound.html;\n\tlocation = \/404notfound.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
